---
title: "Power Simulation"
author: "Byron C. Jaeger and Mike Bancks"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
source(here::here("packages.R"))
tar_load(names = c(results_aim3_gt, results_aim2_gt))

```

## Aim 1

to be filled in

## Aim 2

```{r}
results_aim2_gt |> 
  gt(rowname_col = 'cens') |> 
  tab_stubhead(label = '% Censored') |> 
  cols_move_to_start('static') |> 
  cols_label(static = '0', decay05 = '5', decay10 = '10') |> 
  tab_spanner(columns = c('static', 'decay05', 'decay10'),
              label = '% decay in effect size')
```


to be filled in

## Aim 3

```{r}
results_aim3_gt |> 
  gt(rowname_col = 'cens') |> 
  tab_stubhead(label = '% Censored') |> 
  cols_move_to_start('static') |> 
  cols_label(static = '0', decay10 = '10', decay20 = '20') |> 
  tab_spanner(columns = c('static', 'decay10', 'decay20'),
              label = '% decay in effect size')
```


## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
